### ISSUE TITLE
exception when not using vnc even with it disabled in stf_ios_support

### ISSUE THREAD

**Issue by Bull3time** [DeviceFarmer/stf-ios-provider#2]
Getting the below with the provider continuously shutting down from the fatal error. Reverted to the previous commit (e6fdbe3fb57589c0e486699902f4e2816b1c6227) and it's fine.
``` 
FTL/device 3632 [XXXXXXXX-XXXXXXX] Setup had an error TypeError: r.on is not a function
    at stf_ios_support/repos/stf-ios-provider/lib/units/device-ios/plugins/vncControl.js:38:5
    at SerialSyrup.ParallelSyrup.invoke (stf_ios_support/repos/stf-ios-provider/node_modules/stf-syrup/lib/parallel.js:54:24)
    at stf_ios_support/repos/stf-ios-provider/node_modules/stf-syrup/lib/serial.js:43:33
    at tryCatch1 (stf_ios_support/repos/stf-ios-provider/node_modules/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (stf_ios_support/repos/stf-ios-provider/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:708:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (stf_ios_support/repos/stf-ios-provider/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:724:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (stf_ios_support/repos/stf-ios-provider/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:896:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (stf_ios_support/repos/stf-ios-provider/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (stf_ios_support/repos/stf-ios-provider/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:37:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2020-01-15T10:54:49.993Z FTL/util:lifecycle 3632 [XXXXXXXX-XXXXXXX] Shutting down due to fatal error
```

**Comment by nanoscopic** [comment]
Fixed by this commit: https://github.com/nanoscopic/stf-ios-provider/commit/1a629943df25f3f1fabee4534a3c1167c4482ea9
